PracticaABC/Controllers/InicioController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaABC.Models;
using PracticaABC.Resources;
using PracticaABC.Users.Interface;

using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;


namespace PracticaABC.Controllers
{
    public class InicioController : Controller
    {
        private readonly IUsuarioService _usuarioService;
        public InicioController(IUsuarioService usuarioService){
            _usuarioService = usuarioService;
        }
        public IActionResult IniciarSesion()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> IniciarSesion(string correo, string clave)
        {
            Usuario userFound = await _usuarioService.GetUsuarios(correo, Utilidades.EncryptClave(clave));

            if (userFound == null)
            {
                ViewData["Mensaje"] = "Usuario no encontrado";
                return View();

            }
            List<Claim> claim = new List<Claim>(){
                new Claim(ClaimTypes.Name, userFound.Correo)
            };

            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claim, CookieAuthenticationDefaults.AuthenticationScheme);
            AuthenticationProperties authenticationProperties = new AuthenticationProperties() {
                AllowRefresh = true
            };

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity),
                authenticationProperties
                );
            return RedirectToAction("Index","Home");
        }
    }
}

PracticaABC/Views/Inicio/IniciarSesion.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>IniciarSesion</title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/login.css" rel="stylesheet" />
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
	<div class="login-popup-wrap new_login_popup">
		<div class="login-popup-heading text-center">
			<h4><i class="fa fa-lock" aria-hidden="true"></i> Login </h4>
		</div>
		<form id="loginMember" asp-controller="Inicio" asp-action="IniciarSesion" method="post">
			<div class="form-group">
				<input type="text" class="form-control" id="user_id" placeholder="e-mail" required name="correo">
			</div>
			<div class="form-group">
				<input type="password" class="form-control" id="password" placeholder="Password" required name="clave">
			</div>
			<button type="submit" class="btn btn-default login-popup-btn" name="submit" value="1">Login</button>
			@if (ViewData["Mensaje"] != null)
			{
				<div class="form-group">
					<div class="alert alert-danger" role="alert">
						@ViewData["Mensaje"]
					</div>
				</div>
			}
		</form>
	</div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>